# 异常是什么？

在程序运行中，肯定会遇到各种异常，比如空指针、内存溢出、数组下标越界等。这些都有可能发生，为了避免异常导致程序崩溃，所以我们需要对异常进行处理。

# try catch处理异常

类似于Java一样，C++也可以是使用`try catch`来捕获处理异常。

```c++
int main() {
     try{
         int input = -1;
         int* ints = new int[input];
         delete ints;
     }catch (...){
         cout<< "出现异常了" << endl;
     }
    return 0;
}
```

`catch  ...`表示`catch`块将捕获所有的异常。上面的代码试图分配一个`-1`的堆内存，很荒谬，但是很多时候用户就会这样填，以防万一，我们必须对此类异常进行处理。

**捕获特定异常**

类似Java，C++也可以捕获特定异常，同时也可以具有多个`catch`块。

```c++
 try{
         int input = -1;
         int* ints = new int[input];
         delete ints;
     }catch( bad_alloc& exp){
        cout<< "1"<< endl;
     }catch (...){
         cout<< "2" << endl;
     }
```

此代码最终会打印`1`。

# throw 抛出异常

很多时候，我们需要自己引发异常，这时候就有`trhow`关键字。

```c++
void division(int a){
    if(a==0)
        throw "0不能做被除数";
}
int main() {
     try{
        division( 0 );
     }catch (...){
         cout<< "出现异常了" << endl;
     }
  // catch(const char* s)
    return 0;
}
```

最终会打印出现异常。

如果异常一直没有被处理，那么会一直往上抛。知道找到对应的`catch`块。

# C++标准异常

<img src="https://s2.ax1x.com/2019/12/23/l9EG90.jpg" style="zoom:50%;" />

# std::exception

`bad_alloc&`继承了c++标准类中的`std::exception`。我们在需要引发异常时，可以自定义异常继承`exception`, 好处在于，我们在处理`catch(exception&ex)`时，不但可以处理系统已存在的异常，还能捕获自定义异常，同时自定义异常也更规范、能封装异常信息，更好的查找原因。

很多重要的异常类都是从`std::exception`派生而来：

1. `bad_alloc`：new请求内存失败时引发。
2. `bad_cast`视图使用`dynamic_cast`转换错误类型时引发。
3. `ios_base::failure`:由`iostream`库中的函数和方法引发。

```java
class CustomException: exception{
public:
    string errorMsg;
    int errCode;
    CustomException(string msg, int code):errorMsg(msg),errCode(code){};
};
void checkInput(int a){
    if(a == 0 )
        throw CustomException("兄弟，代码出错了", 001);
}
// 使用自定义异常
int main() {
     try{
         checkInput( 0 );
     }catch( CustomException& exp){
        cout<< exp.errorMsg<< endl;
     }catch(std::exception& e){
       // catch其他异常
     }
    return 0;
}
```

# 总结

 在使用异常时，我们应该自定义异常去继承`std::exception`。

同时需要注意一下使用：

1. 不要在析构函数中引发异常，防止对象回收失败。
2. 不要认为内存总能分配成功，务必将`new`代码放在`try块`中，并使用`catch(std::exception&)`来捕获异常。

3. 不要在`catch()`块中包含实现逻辑或分配资源的代码，以免在处理异常的同时导致异常。











































