# 异常是什么？

在程序运行中，肯定会遇到各种异常，比如空指针、内存溢出、数组下标越界等。这些都有可能发生，为了避免异常导致程序崩溃，所以我们需要对异常进行处理。

# try catch处理异常

类似于Java一样，C++也可以是使用`try catch`来捕获处理异常。

```c++
int main() {
     try{
         int input = -1;
         int* ints = new int[input];
         delete ints;
     }catch (...){
         cout<< "出现异常了" << endl;
     }
    return 0;
}
```

`catch  ...`表示`catch`块将捕获所有的异常。上面的代码试图分配一个`-1`的堆内存，很荒谬，但是很多时候用户就会这样填，以防万一，我们必须对此类异常进行处理。

**捕获特定异常**

类似Java，C++也可以捕获特定异常，同时也可以具有多个`catch`块。

```c++
 try{
         int input = -1;
         int* ints = new int[input];
         delete ints;
     }catch( bad_alloc& exp){
        cout<< "1"<< endl;
     }catch (...){
         cout<< "2" << endl;
     }
```

此代码最终会打印`1`。

# throw 抛出异常

很多时候，















































